#!/usr/bin/env bash

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_DEBUG:-}" ]];then
    set -x
fi

set -euo pipefail

fail(){
    echo "$@"
    exit 1
}

# ===========================
#  Required configuration
# ===========================

# Overridable cluster name
DEFAULT_CLUSTER_NAME="buildkite-${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_RETRY_COUNT}"
ANYSCALE_CLUSTER_NAME="${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_NAME:-$DEFAULT_CLUSTER_NAME}"
export ANYSCALE_CLUSTER_NAME

# Allow 'ray job submit' support, etc
# https://docs.anyscale.com/develop/workspaces/interactive-development#minimalist-guide-on-using-ray-jobs
RAY_ADDRESS="anyscale://$ANYSCALE_CLUSTER_NAME"
export RAY_ADDRESS

DOCKER_OPTIONS=(
    run
    -it
    --entrypoint anyscale
    -e ANYSCALE_CLI_TOKEN
    -e ANYSCALE_HOST
    )

DOCKER_CMD=(
    cluster start
    --name "$ANYSCALE_CLUSTER_NAME"
    --env "$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_ENV_NAME"
    )

# ===========================
#  Optional configuration
# ===========================

# This is where we will mount configs into the container
CONTAINER_COMPUTE_DIR=/configs

DOCKER="${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_DOCKER_CMD:-docker}"
IMAGE="${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_IMAGE:-anyscale/ray:2.8.0}"

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_COMPUTE_NAME:-}" ]];then
    DOCKER_CMD+=(--compute "$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_COMPUTE_NAME")
fi

# File path to compute configuration data file (json, yaml)
# NOTE: this path is _relative_ to the buildkite job's workdir
if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_COMPUTE_FILE:-}" ]];then
    DOCKER_OPTION+=(-v "$(pwd):$CONTAINER_COMPUTE_DIR")
    DOCKER_CMD+=(--compute-file "$CONTAINER_COMPUTE_DIR/$BUILDKITE_PLUGIN_ANYSCALE_COMPUTE_FILE")
fi

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_NAME:-}" ]];then
    DOCKER_CMD+=(--project "$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_NAME")
    ANYSCALE_PROJECT_NAME="$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_NAME"
    export ANYSCALE_PROJECT_NAME
fi

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_ID:-}" ]];then
    DOCKER_CMD+=(--project-id "$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_ID")
    ANYSCALE_PROJECT_ID="$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_PROJECT_ID"
    export ANYSCALE_PROJECT_ID
fi

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_CLOUD_NAME:-}" ]];then
    DOCKER_CMD+=(--cloud-name "$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_CLOUD_NAME")
    ANYSCALE_CLOUD_NAME="$BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_CLOUD_NAME"
    export ANYSCALE_CLOUD_NAME
fi

if [[ -n "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_IDLE_TIMEOUT:-}" ]];then
    DOCKER_CMD+=(--idle-timeout "${BUILDKITE_PLUGIN_ANYSCALE_CLUSTER_IDLE_TIMEOUT:-10}")
fi

if [[ -z "${ANYSCALE_CLI_TOKEN:-}" ]];then
    fail "'ANYSCALE_CLI_TOKEN' environment variable is missing or empty - have you tried the anyscale-credentials-buildkite-plugin?"
fi

"$DOCKER" "${DOCKER_OPTIONS[@]}" "$IMAGE" "${DOCKER_CMD[@]}"

echo "--- :anyscale: Started cluster: $ANYSCALE_CLUSTER_NAME"

buildkite agent annotate --context anyscale_cluster --style INFO <<-EOL
:anyscale: Cluster: \`$ANYSCALE_CLUSTER_NAME\` (started)
EOL
